# Generated by Django 4.1.1 on 2022-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=28)),
                ('bank_location', models.CharField(max_length=39)),
                ('opp_amount', models.IntegerField()),
                ('holder_name', models.CharField(max_length=23)),
                ('holder_location', models.CharField(max_length=37)),
            ],
        ),
    ]
